export interface IClockTransaction {
    id: number;
    emp_code: string;
    punch_time: string;
    punch_state: string;
    verify_type: number;
    work_code: string;
    terminal_sn: string;
    terminal_alias: string | null;
    area_alias: string | null;
    longitude: number | null;
    latitude: number | null;
    gps_location: string | null;
    mobile: string | null;
    source: number;
    purpose: number;
    crc: string | null;
    is_attendance: boolean | null;
    reserved: string | null;
    upload_time: string;
    sync_status: string | null;
    sync_time: string | null;
    is_mask: number;
    temperature: string | null;
    emp: number | null;
    terminal: number | 0;
    // Nuevo campo para indicar si llegó a tiempo ("a_tiempo", "tarde", "sin_horario")
    llegoATiempo?: 'a_tiempo' | 'tarde' | 'sin_horario';
}


// new model for the response generated by json data
/**
 * "id": 1683659,
        "empCode": "76095492",
        "punchTime": "2025-07-17T07:40:21",
        "punchState": "0",
        "verifyType": 1,
        "workCode": "",
        "terminalSn": "AEH2201960011",
        "terminalAlias": "CH2-SAL",
        "areaAlias": "CHILCA2",
        "longitude": null,
        "latitude": null,
        "gpsLocation": null,
        "mobile": null,
        "source": 1,
        "purpose": 9,
        "crc": "AAHAEAAACABAAAHABAHA",
        "isAttendance": null,
        "uploadTime": "2025-07-17T07:40:15",
        "syncStatus": null,
        "syncTime": null,
        "empId": 4657,
        "terminalId": 7,
        "isMask": 255,
        "temperature": 255
 */
export interface IClockTransactionResponse2 {
    id: number;
    empCode: string;
    punchTime: string;
    punchState: string;
    verifyType: number;
    workCode: string;
    terminalSn: string;
    terminalAlias: string | null;
    areaAlias: string | null;
    longitude: number | 0;
    latitude: number | 0;
    gpsLocation: string | null;
    mobile: string | null;
    source: number | 0;
    purpose: number | 0;
    crc: string | null;
    isAttendance: boolean | null;
    uploadTime: string;
    syncStatus: string | null;
    syncTime: string | null;
    empId: number | 0;
    terminalId: number | 0;
    isMask: number | 0;
    temperature: string | null;
}


export interface IClockTransactionResponse {
    count: number;
    next: string | null;
    previous: string | null;
    msg: string;
    code: number;
    data: IClockTransaction[];
}

export interface IClockTransactionParams {
    emp_code?: string;
    page_size?: number;
    page?: number;
    start_time?: string;
}

export interface IClockTransactionParams2 {
    empCode?: string;
    personalId?:string,
    startDate?: string;
    endDate?: string;
    page?: number;  
    pageSize?: number;
}
